spring.application.name=graduation-backend
server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=${SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=${THYMELEAF_CACHE:true}
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
